version: '3'

services:
    python:
        image: python:3.6
        volumes:
            - ./blog:/blog
        ports:
            - 8001:8001
        command: bash -c "cd ./blog && pip install -r requirements.txt && python manage.py migrate && gunicorn blog.wsgi 0.0.0.0:8001"
