# Generated by Django 4.0.5 on 2022-06-04 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_comment_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
